### ISSUE TITLE
Requirements for zoneminder

### ISSUE THREAD

**Issue by freedomlives** [MalakymR/mkr-overlay#3]
Hi,
There was one which I already forgot, but now, trying to run zmonvif-probe.pl, I've needed to emerge the following perl modules:
Params-Util
Data-UUID
IO-Socket-Multicast
These should be made dependencies, I suppose.

**Comment by MalakymR** [comment]
I checked and it seems to work fine (although one error before it finds cameras).

> Name "ZoneMinder::ONVIF::verbose" used only once: possible typo at /usr/bin/zmonvif-probe.pl line 8

Data-UUID and IO-Socket-Multicast are already in DEPEND.

Can you find the other(s) you were missing and the error you received?

**Comment by freedomlives** [comment]
It may have been my mistake, that at some point a different overlay got used for the ebuild.
